---
- name: "Playbook to copy apps"
  hosts: "{{ host }}"
  #  become: true
  vars:
    - serv: "{{ service }}"
  tasks:
    - name: copy the config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      - { src: '{{ job }}/{{ serv }}/{{ serv }}.properties', dest: '{{ path }}/{{ serv }}lib/' }
      - { src: '{{ job }}/{{ serv }}/serverconfiguration_{{ serv }}.xml', dest: '{{ path }}/{{ serv}}lib/serverconfig/' }
      - { src: '{{ job }}/{{ serv }}/middleware_{{ serv }}.xml', dest: '{{ path }}/{{ serv }}lib/serverconfig/'}
      - { src: '{{ job }}/log4j.xml', dest: '{{ path }}/lib/'}  
      when: (serv== "realpool") or (serv== "realstake") or (serv== "ptrealpool") or (serv== "ptrealstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "playstake") 

    - name: copy the scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0755
      with_items:
      - { src: '{{ job }}/{{ serv }}/scripts/', dest: '{{ path }}/gsa/{{ serv }}'}
        #when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "ptrealpool") or (serv== "ptrealstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat")  or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap") or (serv == "a23analytics")
      when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "ptrealpool") or (serv== "ptrealstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat")  or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap")
    - name: copy the scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0755
      with_items:
      - { src: '{{ job }}/{{ serv }}/scripts/', dest: '{{ path }}/{{ serv }}/bin/'}
        #when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "ptrealpool") or (serv== "ptrealstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat")  or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap") or (serv == "a23analytics")
      when: (serv == "Ace23Analytics") or (serv== "Ace2ThreeService")
    - name: copy the sslcerts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0755
      with_items:
      - { src: '{{ job }}/{{ serv }}/ssl/', dest: '{{ path }}/{{ serv }}lib/ssl/'}  
      when: (serv == "lobby") 
      #when: (serv == "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "playpool") or (serv== "playstake") or (serv== "gamerulesengine") or (serv== "longertourneynode") or (serv== "oldtourneynode")


    - name: copy the chat & bridge config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      - { src: '{{ job }}/{{ serv }}/{{ serv }}.properties', dest: '{{ path }}/{{ serv }}lib/' }
      - { src: '{{ job }}/{{ serv }}/serverconfiguration_{{ serv }}.xml', dest: '{{ path }}/{{ serv}}lib/serverconfig/' }
      - { src: '{{ job }}/log4j.xml', dest: '{{ path }}/lib/'}  
      when: (serv== "chat") or (serv== "a23bridge")


    - name: copy the FraudRules file for realpool & realstake
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      - { src: '{{ job }}/FraudRules.properties', dest: '{{ path }}/lib/'}  
      when: (serv== "realpool") or (serv== "realstake") 
    - name: copy the DB properties files
      copy:
        src: "{{ item.src }}"
        dest: "{{ path }}/{{ serv }}lib/"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:
        - { src: '{{ job }}/{{ serv }}/DB_{{ serv }}.properties'}
      when: (serv == "realpool") or (serv == "realstake")


    - name: copy the a23service config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      - { src: '{{ job }}/{{ serv }}/', dest: '/opt/ace2three/newgameserver/Ace2ThreeService/jobs_config_service/' }
        #- { src: '{{ job }}/{{ serv }}/*.xml', dest: '/opt/ace2three/newgameserver/a23service/jobs_config_service/' }
        #- { src: '{{ job }}/{{ serv }}/serverconfiguration_{{ serv }}.xml', dest: '/opt/ace2three/newgameserver/a23service/jobs_config_service/' }
        #      - { src: '{{ job }}/log4j.xml', dest: '/opt/ace2three/newgameserver/a23service/lib/'}  
      when: ( serv == "Ace2ThreeService") 


    - name: copy the a23analytics config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      - { src: '{{ job }}/{{ serv }}/', dest: '/opt/ace2three/newgameserver/Ace23Analytics/jobs_config_analytics/' }
        #- { src: '{{ job }}/{{ serv }}/*.xml', dest: '/opt/ace2three/newgameserver/a23analytics/jobs_config_analytics/' }
        #- { src: '{{ job }}/{{ serv }}/cassandra.properties', dest: '/opt/ace2three/newgameserver/a23analytics/jobs_config_analytics/' }
        #- { src: '{{ job }}/{{ serv }}/serverconfiguration_{{ serv }}.xml', dest: '/opt/ace2three/newgameserver/a23analytics/jobs_config_analytics/' }
        #      - { src: '{{ job }}/log4j.xml', dest: '/opt/ace2three/newgameserver/a23analytics/lib/'}  
      when: ( serv == "Ace23Analytics") 

      #    - name: copy the a23service scripts
      #      copy:
      #        src: "{{ item.src }}"
      #        dest: "{{ item.dest }}"
      #        owner: gameadmin
      #        group: gameadmin
      #        mode: 0777
      #      with_items:
      #      - { src: '{{ job }}/{{ serv }}/scripts/', dest: '/opt/ace2three/newgameserver/a23service/bin/'}
      #      when: (serv == "a23service") 
      #
      #    - name: copy the a23analytics scripts
      #      copy:
      #       src: "{{ item.src }}"
      #       dest: "{{ item.dest }}"
      #       owner: gameadmin
      #       group: gameadmin
      #       mode: 0777
      #      with_items:
      #      - { src: '{{ job }}/{{ serv }}/scripts/', dest: '/opt/ace2three/newgameserver/a23analytics/bin'}
      #      when: (serv == "a23analytics")


    - name: copy the lobby config files
      copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: gameadmin
       group: gameadmin
       mode: 0644
      with_items:
      - { src: '{{ job }}/{{ serv }}/common{{ serv }}.properties', dest: '/home/gameadmin/{{ serv }}/' }
      - { src: '{{ job }}/{{ serv }}/{{ hosts }}.properties', dest: '/home/gameadmin/{{ serv }}/' }
      - { src: '{{ job }}/{{ serv }}/serverconfiguration_{{ serv }}.xml', dest: '{{ path }}/{{ serv}}lib/serverconfig/' }
      - { src: '{{ job }}/{{ serv }}/middleware_{{ serv }}.xml', dest: '{{ path }}/{{ serv }}lib/serverconfig/'}
      - { src: '{{ job }}/log4j.xml', dest: '{{ path }}/lib/'}
      when: (serv == "lobby") and (hosts == "lobby1") or ( serv == "lobby" ) and (hosts == "lobby2")




      #  - name: copy the lobby config files
      #  copy:
      #    src: "{{ item.src }}"
      #    dest: "{{ item.dest }}"
      #    owner: gameadmin
      #    group: gameadmin
      #    mode: 0644
      #  with_items:
      #  - { src: '{{ job }}/{{ serv }}/serverconfiguration_{{ serv }}.xml', dest: '{{ path }}/{{ serv}}lib/serverconfig/' }
      #  - { src: '{{ job }}/{{ serv }}/middleware_{{ serv }}.xml', dest: '{{ path }}/{{ serv }}lib/serverconfig/'}
      #  - { src: '{{ job }}/log4j.xml', dest: '{{ path }}/lib/'}
      #  when: ( serv == "lobby")

      #  name: delete lobby from /home/gameadmin
      #  file:
      #    path: /home/gameadmin/lobby
      #    state: absent


      #    #- name: copy the lobby config files
      #  #copy:
      #  #src: "{{ item.src }}"
      #  # dest: "{{ item.dest }}"
      #  # owner: gameadmin
      #    group: gameadmin
      #    mode: 0644
      #  with_items:
      #  - { src: '{{ job }}/{{ serv }}/common{{ serv }}.properties', dest: '/home/gameadmin/{{ serv }}/' }
      #  - { src: '{{ job }}/{{ serv }}/{{ hosts }}.properties', dest: '/home/gameadmin/{{ serv }}/' }
      #  when: (hosts == "lobby1") or (hosts == "lobby2")      
      #ignore_errors: true

    - name: merge lobby properties
      assemble:
        src: "/home/gameadmin/{{ serv }}"
        dest: mergedfile
      when: ( serv == "lobby") 

    - name: Find uniqe entries
      shell: cat mergedfile  > "{{ path }}/{{ serv }}lib/{{ serv }}.properties"
      #shell: cat mergedfile | sort -u | uniq -u > "{{ path }}/{{ serv }}lib/{{ serv }}.properties"
      when: ( serv == "lobby") 

    - name: stop the {{ serv }} service
      shell: sh {{ path }}/gsa/{{ serv }}/stop{{ serv }}.sh
      when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat") or (serv== "ace23service") or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap")  or (serv== "ptrealpool") or (serv== "ptrealstake")
      ignore_errors: true

    - name: stop a23service
      #shell: sh /opt/ace2three/newgameserver/a23service/bin/shutdown.sh {{ env }}
      local_action: shell /home/devops/ansible/core-lobby/tomcatscripts/core-stopa23service.sh {{ envi }}
      when: (serv== "Ace2ThreeService") 
      ignore_errors: true

    - name: stop a23analytics
      #shell: sh /opt/ace2three/newgameserver/a23analytics/bin/shutdown.sh {{ env }}
      local_action: shell /home/devops/ansible/core-lobby/tomcatscripts/core-stopa23analytics.sh {{ envi }}
    
      # shell: sh shutdown.sh
      # args:
      # chdir: /opt/ace2three/newgameserver/apache-tomcat-9.0.71/bin/
          #chdir: /opt/ace2three/newgameserver/apache-tomcat-9.0.71/bin
      when: (serv== "Ace23Analytics") 
      ignore_errors: true

      #    - name: export catalina base to a23service
      #      shell: export CATALINA_BASE=/opt/ace2three/apache-tomcat-8.0.26/
      #      when: (serv== "a23service") 



    - name: start a23service
      #shell: sh /opt/ace2three/newgameserver/a23service/bin/startup.sh {{ env }}
      #shell: sh /opt/ace2three/newgameserver/apache-tomcat-9.0.11/bin/startup.sh
      #shell: systemctl restart tomcat 
      local_action: shell /home/devops/ansible/core-lobby/tomcatscripts/core-starta23service.sh {{ envi }}
      when: (serv== "Ace2ThreeService") 

      #    - name: start a23analytics
      #      #shell: sh /opt/ace2three/apache-tomcat-9.0.11/bin/starta23analytics.sh
      #      shell: systemctl start tomcat9
      #      when: (serv== "a23analytics") 


      #    - name: start a23analytics
      #      shell: sh /opt/ace2three/apache-tomcat-9.0.11/bin/starta23analytics.sh
      #      #shell: systemctl start tomcat9
      #      local_action:  shell /home/devops/ansible/core-lobby/starttomcat9analytics.sh
      #      # args:
      #      # chdir: /home/devops/ansible/core-lobby/
      #      when: (serv== "a23analytics") 


    - name: start a23analytics
      #shell: bash /opt/ace2three/newgameserver/a23analytics/bin/startup.sh {{ env }}
      #shell: systemctl start tomcat9
      #local_action: shell /home/devops/ansible/core-lobby/tomcatscripts/core-starta23analytics.sh
      local_action: shell /home/devops/ansible/core-lobby/tomcatscripts/core-starta23analytics.sh {{ envi }}
      #args:
                #chdir: /home/devops/ansible/core-lobby/
                # chdir: /opt/ace2three/newgameserver/apache-tomcat-9.0.71/bin/
      when: (serv== "Ace23Analytics") 


      #    - name: merge lobby properties
      #      assemble:
      #        src: '{{ path }}/{{ serv }}lib/{{ hosts }}.properties'
      #        dest: '{{ path }}/{{ serv }}lib/{{ serv }}.properties'


      #    - name: merge lobby properties
      #      command: cat {{ path }}/{{ serv }}lib/{{ hosts }}.properties >> {{ path }}/{{ serv }}lib/{{ serv }}.properties


      #    - name: start the service
      #      command: sh {{ path }}/gsa/{{ serv }}/run.sh
      #      when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat") or (serv== "ace23service") or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap") or (serv== "ptrealpool") or (serv== "ptrealstake")

    - name: start the service
      shell: sh run.sh
          #chdir: "{{ path }}/gsa/{{ serv }}"
      args:
        chdir: "{{ path }}/gsa/{{ serv }}"
      when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat") or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap") or (serv== "ptrealpool") or (serv== "ptrealstake")
    

    - name: Service running logs
      shell: ps -ef| grep {{serv}}
      when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap") or (serv== "ptrealpool") or (serv== "ptrealstake")
      register: output
      failed_when: '"java -classpath" not in output.stdout'
     

    - debug:
        var: "output.stdout_lines"

    - name: Service running logs
      shell: ps -ef| grep {{serv}}
      when: (serv== "a23bridge")
      register: outputA
      failed_when: '"java -Dspring.profiles.active" not in outputA.stdout'

    - debug:
        var: "outputA.stdout_lines"

    - name: Service running logs
      shell: ps -ef| grep {{serv}}
      when: (serv== "Ace2ThreeService") or (serv== "Ace23Analytics")
      register: outputT
      failed_when: '"Djava" not in outputT.stdout'

    - debug:
        var: "outputT.stdout_lines"

        #  - name: Service up or not 
        #    shell: |
        #       if [ $(echo output | grep Djava) ] && [ $(echo output | grep {{ serv }}) ]; then
        #       tag = 0
        #       fi
        #    register: tag
        #    failed_when: tag == 0


      #   - name: check the service is up and running
      #shell: ps -ef| grep {{serv}}
      #when: (serv== "lobby") or (serv== "realpool") or (serv== "realstake") or (serv== "playpool") or (serv == "longertourneymaster") or (serv== "longertourneynode") or (serv== "oldtourneymaster") or (serv== "oldtourneynode") or (serv== "tourneyrank") or (serv== "chat") or (serv== "a23service") or (serv== "a23bridge") or (serv== "gamerulesengine") or (serv== "playstake") or (serv== "clevertap") or (serv== "ptrealpool") or (serv== "ptrealstake") or (serv == "a23analytics")
      #register: output

      # - debug: var = "{{output.stdout_lines}}"

      #- name: Checking if the service is up
      #local_action: shell /home/devops/ansible/core-lobby/tomcatscripts/core-starta23analytics.sh
      #args:
                #chdir: /home/devops/ansible/core-lobby/
                # chdir: /opt/ace2three/newgameserver/apache-tomcat-9.0.71/bin/
                #when: (serv== "a23analytics")
      #register: idvalue
      #changed_when: false  
      
      #shell: echo 'service is up and running'
      
      #debug: 
      #  msg: "Service is up and running"
      #when: (serv== "a23analytics") or (serv== "a23service") and (idvalue > 0)
     

      #      - name: start the servcie
      #        shell: sh /home/gameadmin/{{ serv }}/scripts/stop{{ serv }}.sh
      #        user: gameadmin
