---
- name: "Playbook to build artifactory server jobs"
  hosts: "{{ host }}"
  #become: true
  #vars:

  tasks:
    - name: "update hostfile at destination"
      become: true
      shell: ansible-playbook update-hostfile.yml --limit "rnd-lobby2,rnd-lobby3,rnd-lobby4"
