---
- name: "Playbook to copy apps"
  hosts: "{{ host }}"
  #  become: true
  vars:
    - serv: "{{ service }}"
  tasks:
    - name: copy the scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0755
      with_items:
      - { src: '{{ job }}/{{ hosts }}/scripts/', dest: '{{ path }}/gsa/{{ serv }}'}
      when: (serv== "lobby")  

    - name: copy the sslcerts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0755
      with_items:
      - { src: '{{ job }}/ssl/', dest: '{{ path }}/lib/ssl/'}  
      when: (serv == "lobby") 


    - name: copy the lobby config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      - { src: '{{ job }}/{{ hosts }}/serverconfiguration_{{ serv }}.xml', dest: '{{ path }}/{{ serv}}lib/serverconfig/' }
      - { src: '{{ job }}/{{ hosts }}/middleware_{{ serv }}.xml', dest: '{{ path }}/{{ serv }}lib/serverconfig/'}
      - { src: '{{ job }}/log4j.xml', dest: '{{ path }}/lib/'} 
      when: ( serv == "lobby") 

    - name: delete lobby from /home/gameadmin
      file: 
        path: /home/gameadmin/lobby
        state: absent


    - name: copy the lobby config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: gameadmin
        group: gameadmin
        mode: 0644
      with_items:        
      # - { src: '{{ job }}/{{ hosts }}/common{{ serv }}.properties', dest: '/home/gameadmin/{{ serv }}/' }
      - { src: '{{ job }}/{{ hosts }}/{{ serv }}.properties', dest: '/home/gameadmin/{{ serv }}/' }
        #when: (hosts == "lobby1") or (hosts == "lobby2") 
      when: ( serv == "lobby")


    - name: merge lobby properties
      assemble:
        src: "/home/gameadmin/{{ serv }}"
        dest: mergedfile
      when: ( serv == "lobby") 

    - name: Find uniqe entries
      shell: cat mergedfile  > "{{ path }}/{{ serv }}lib/{{ serv }}.properties"
      when: ( serv == "lobby")  

    - name: stop the servcie
      shell: sh {{ path }}/gsa/{{ serv }}/stop{{ serv }}.sh
      when: ( serv == "lobby") 

      #    - name: start the service
      #      command: sh {{ path }}/gsa/{{ serv }}/run.sh
      #      when: ( serv == "lobby") 

    - name: start the service
      shell: sh run.sh
      #chdir: "{{ path }}/gsa/{{ serv }}"
      args:
        chdir: "{{ path }}/gsa/{{ serv }}"
      when: ( serv == "lobby")

    - name: Service running logs
      shell: ps -ef| grep {{serv}}
      when: (serv== "lobby") 
      register: output
      failed_when: '"java -classpath" not in output.stdout'

    - debug:
        var: "output.stdout_lines"
