---
- name: "Playbook to copy apps"
  hosts: "{{ host }}"
  #  become: true
  vars:
    - serv: "{{ service }}"
  tasks:

    - name: Display paths of all {{ serv }} files in dir
      debug: msg={{ lookup('fileglob', '{{ job }}/target/{{ serv }}*.jar') }}


    - name: Copy war files
      ansible.builtin.copy:
        src: "{{ item }}"
        #dest: "{{ path }}/tomcat/webapps/{{ serv }}/"
        dest: "{{ path2 }}/{{ serv }}"
        owner: "devops"
        group: "devops"
        mode: 0600
      with_fileglob:
        - '{{ job }}/target/*.war'
      when: (serv== "AceAdmin") or (serv== "Ace2Three")

    - name: Copy the deployment files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: devops
        group: devops
        mode: 0777
      with_items:
      - { src: '/home/devops/ansible/ec2scripts/admin-deploy.sh', dest: '/home/devops' }
      - { src: '/home/devops/ansible/ec2scripts/admin-private-playbook.yml', dest: '/home/devops' }
      when: (serv== "AceAdmin") or (serv== "Ace2Three")


     - name: "Execute main playbook for deploying in private instance"
       shell: sh /home/devops/admin-deploy.sh {{ target_host }} {{ service }} {{ path }} {{ path2 }}
       when: (serv== "AceAdmin") or (serv== "Ace2Three")
